'use strict';

app.value('REGION', [{
    id: 1,
    name: '爱公馆',
    buildings: [{
        id: 4,
        name: '四号楼',
        units: [{
            id: 1,
            name: '一单元',
            houseNumbers: [{
                id: 101,
                name: '101'
            }, {
                id: 102,
                name: '102'
            }, {
                id: 103,
                name: '103'
            }, {
                id: 104,
                name: '104'
            }, {
                id: 105,
                name: '105'
            }, {
                id: 106,
                name: '106'
            }, {
                id: 107,
                name: '107'
            }, {
                id: 108,
                name: '108'
            }, {
                id: 201,
                name: '201'
            }, {
                id: 202,
                name: '202'
            }, {
                id: 203,
                name: '203'
            }, {
                id: 204,
                name: '204'
            }, {
                id: 205,
                name: '205'
            }, {
                id: 206,
                name: '206'
            }, {
                id: 207,
                name: '207'
            }, {
                id: 208,
                name: '208'
            }, {
                id: 301,
                name: '301'
            }, {
                id: 302,
                name: '302'
            }, {
                id: 303,
                name: '303'
            }, {
                id: 304,
                name: '304'
            }, {
                id: 305,
                name: '305'
            }, {
                id: 306,
                name: '306'
            }, {
                id: 307,
                name: '307'
            }, {
                id: 308,
                name: '308'
            }, {
                id: 401,
                name: '401'
            }, {
                id: 402,
                name: '402'
            }, {
                id: 403,
                name: '403'
            }, {
                id: 404,
                name: '404'
            }, {
                id: 405,
                name: '405'
            }, {
                id: 406,
                name: '406'
            }, {
                id: 407,
                name: '407'
            }, {
                id: 408,
                name: '408'
            }, {
                id: 501,
                name: '501'
            }, {
                id: 502,
                name: '502'
            }, {
                id: 503,
                name: '503'
            }, {
                id: 504,
                name: '504'
            }, {
                id: 505,
                name: '505'
            }, {
                id: 506,
                name: '506'
            }, {
                id: 507,
                name: '507'
            }, {
                id: 508,
                name: '508'
            }, {
                id: 601,
                name: '601'
            }, {
                id: 602,
                name: '602'
            }, {
                id: 603,
                name: '603'
            }, {
                id: 604,
                name: '604'
            }, {
                id: 605,
                name: '605'
            }, {
                id: 606,
                name: '606'
            }, {
                id: 607,
                name: '607'
            }, {
                id: 608,
                name: '608'
            }, {
                id: 701,
                name: '701'
            }, {
                id: 702,
                name: '702'
            }, {
                id: 703,
                name: '703'
            }, {
                id: 704,
                name: '704'
            }, {
                id: 705,
                name: '705'
            }, {
                id: 706,
                name: '706'
            }, {
                id: 707,
                name: '707'
            }, {
                id: 708,
                name: '708'
            }, {
                id: 801,
                name: '801'
            }, {
                id: 802,
                name: '802'
            }, {
                id: 803,
                name: '803'
            }, {
                id: 804,
                name: '804'
            }, {
                id: 805,
                name: '805'
            }, {
                id: 806,
                name: '806'
            }, {
                id: 807,
                name: '807'
            }, {
                id: 808,
                name: '808'
            }, {
                id: 901,
                name: '901'
            }, {
                id: 902,
                name: '902'
            }, {
                id: 903,
                name: '903'
            }, {
                id: 904,
                name: '904'
            }, {
                id: 905,
                name: '905'
            }, {
                id: 906,
                name: '906'
            }, {
                id: 907,
                name: '907'
            }, {
                id: 908,
                name: '908'
            }, {
                id: 1001,
                name: '1001'
            }, {
                id: 1002,
                name: '1002'
            }, {
                id: 1003,
                name: '1003'
            }, {
                id: 1004,
                name: '1004'
            }, {
                id: 1005,
                name: '1005'
            }, {
                id: 1006,
                name: '1006'
            }, {
                id: 1007,
                name: '1007'
            }, {
                id: 1008,
                name: '1008'
            }, {
                id: 1101,
                name: '1101'
            }, {
                id: 1102,
                name: '1102'
            }, {
                id: 1103,
                name: '1103'
            }, {
                id: 1104,
                name: '1104'
            }, {
                id: 1105,
                name: '1105'
            }, {
                id: 1106,
                name: '1106'
            }, {
                id: 1107,
                name: '1107'
            }, {
                id: 1108,
                name: '1108'
            }, {
                id: 1201,
                name: '1201'
            }, {
                id: 1202,
                name: '1202'
            }, {
                id: 1203,
                name: '1203'
            }, {
                id: 1204,
                name: '1204'
            }, {
                id: 1205,
                name: '1205'
            }, {
                id: 1206,
                name: '1206'
            }, {
                id: 1207,
                name: '1207'
            }, {
                id: 1208,
                name: '1208'
            }, {
                id: 1301,
                name: '1301'
            }, {
                id: 1302,
                name: '1302'
            }, {
                id: 1303,
                name: '1303'
            }, {
                id: 1304,
                name: '1304'
            }, {
                id: 1305,
                name: '1305'
            }, {
                id: 1306,
                name: '1306'
            }, {
                id: 1307,
                name: '1307'
            }, {
                id: 1308,
                name: '1308'
            }, {
                id: 1401,
                name: '1401'
            }, {
                id: 1402,
                name: '1402'
            }, {
                id: 1403,
                name: '1403'
            }, {
                id: 1404,
                name: '1404'
            }, {
                id: 1405,
                name: '1405'
            }, {
                id: 1406,
                name: '1406'
            }, {
                id: 1407,
                name: '1407'
            }, {
                id: 1408,
                name: '1408'
            }, {
                id: 1501,
                name: '1501'
            }, {
                id: 1502,
                name: '1502'
            }, {
                id: 1503,
                name: '1503'
            }, {
                id: 1504,
                name: '1504'
            }, {
                id: 1505,
                name: '1505'
            }, {
                id: 1506,
                name: '1506'
            }, {
                id: 1507,
                name: '1507'
            }, {
                id: 1508,
                name: '1508'
            }, {
                id: 1601,
                name: '1601'
            }, {
                id: 1602,
                name: '1602'
            }, {
                id: 1603,
                name: '1603'
            }, {
                id: 1604,
                name: '1604'
            }, {
                id: 1605,
                name: '1605'
            }, {
                id: 1606,
                name: '1606'
            }, {
                id: 1607,
                name: '1607'
            }, {
                id: 1608,
                name: '1608'
            }, {
                id: 1701,
                name: '1701'
            }, {
                id: 1702,
                name: '1702'
            }, {
                id: 1703,
                name: '1703'
            }, {
                id: 1704,
                name: '1704'
            }, {
                id: 1705,
                name: '1705'
            }, {
                id: 1706,
                name: '1706'
            }, {
                id: 1707,
                name: '1707'
            }, {
                id: 1708,
                name: '1708'
            }, {
                id: 1801,
                name: '1801'
            }, {
                id: 1802,
                name: '1802'
            }, {
                id: 1803,
                name: '1803'
            }, {
                id: 1804,
                name: '1804'
            }, {
                id: 1805,
                name: '1805'
            }, {
                id: 1806,
                name: '1806'
            }]
        }]
    }, {
        id: 5,
        name: '五号楼',
        units: [{
            id: 1,
            name: '一单元',
            houseNumbers: [{
                id: 101,
                name: '101'
            }, {
                id: 102,
                name: '102'
            }, {
                id: 103,
                name: '103'
            }, {
                id: 104,
                name: '104'
            }, {
                id: 105,
                name: '105'
            }, {
                id: 106,
                name: '106'
            }, {
                id: 107,
                name: '107'
            }, {
                id: 108,
                name: '108'
            }, {
                id: 201,
                name: '201'
            }, {
                id: 202,
                name: '202'
            }, {
                id: 203,
                name: '203'
            }, {
                id: 204,
                name: '204'
            }, {
                id: 205,
                name: '205'
            }, {
                id: 206,
                name: '206'
            }, {
                id: 207,
                name: '207'
            }, {
                id: 208,
                name: '208'
            }, {
                id: 301,
                name: '301'
            }, {
                id: 302,
                name: '302'
            }, {
                id: 303,
                name: '303'
            }, {
                id: 304,
                name: '304'
            }, {
                id: 305,
                name: '305'
            }, {
                id: 306,
                name: '306'
            }, {
                id: 307,
                name: '307'
            }, {
                id: 308,
                name: '308'
            }, {
                id: 401,
                name: '401'
            }, {
                id: 402,
                name: '402'
            }, {
                id: 403,
                name: '403'
            }, {
                id: 404,
                name: '404'
            }, {
                id: 405,
                name: '405'
            }, {
                id: 406,
                name: '406'
            }, {
                id: 407,
                name: '407'
            }, {
                id: 408,
                name: '408'
            }, {
                id: 501,
                name: '501'
            }, {
                id: 502,
                name: '502'
            }, {
                id: 503,
                name: '503'
            }, {
                id: 504,
                name: '504'
            }, {
                id: 505,
                name: '505'
            }, {
                id: 506,
                name: '506'
            }, {
                id: 507,
                name: '507'
            }, {
                id: 508,
                name: '508'
            }, {
                id: 601,
                name: '601'
            }, {
                id: 602,
                name: '602'
            }, {
                id: 603,
                name: '603'
            }, {
                id: 604,
                name: '604'
            }, {
                id: 605,
                name: '605'
            }, {
                id: 606,
                name: '606'
            }, {
                id: 607,
                name: '607'
            }, {
                id: 608,
                name: '608'
            }, {
                id: 701,
                name: '701'
            }, {
                id: 702,
                name: '702'
            }, {
                id: 703,
                name: '703'
            }, {
                id: 704,
                name: '704'
            }, {
                id: 705,
                name: '705'
            }, {
                id: 706,
                name: '706'
            }, {
                id: 707,
                name: '707'
            }, {
                id: 708,
                name: '708'
            }, {
                id: 801,
                name: '801'
            }, {
                id: 802,
                name: '802'
            }, {
                id: 803,
                name: '803'
            }, {
                id: 804,
                name: '804'
            }, {
                id: 805,
                name: '805'
            }, {
                id: 806,
                name: '806'
            }, {
                id: 807,
                name: '807'
            }, {
                id: 808,
                name: '808'
            }, {
                id: 901,
                name: '901'
            }, {
                id: 902,
                name: '902'
            }, {
                id: 903,
                name: '903'
            }, {
                id: 904,
                name: '904'
            }, {
                id: 905,
                name: '905'
            }, {
                id: 906,
                name: '906'
            }, {
                id: 907,
                name: '907'
            }, {
                id: 908,
                name: '908'
            }, {
                id: 1001,
                name: '1001'
            }, {
                id: 1002,
                name: '1002'
            }, {
                id: 1003,
                name: '1003'
            }, {
                id: 1004,
                name: '1004'
            }, {
                id: 1005,
                name: '1005'
            }, {
                id: 1006,
                name: '1006'
            }, {
                id: 1007,
                name: '1007'
            }, {
                id: 1008,
                name: '1008'
            }, {
                id: 1101,
                name: '1101'
            }, {
                id: 1102,
                name: '1102'
            }, {
                id: 1103,
                name: '1103'
            }, {
                id: 1104,
                name: '1104'
            }, {
                id: 1105,
                name: '1105'
            }, {
                id: 1106,
                name: '1106'
            }, {
                id: 1107,
                name: '1107'
            }, {
                id: 1108,
                name: '1108'
            }, {
                id: 1201,
                name: '1201'
            }, {
                id: 1202,
                name: '1202'
            }, {
                id: 1203,
                name: '1203'
            }, {
                id: 1204,
                name: '1204'
            }, {
                id: 1205,
                name: '1205'
            }, {
                id: 1206,
                name: '1206'
            }, {
                id: 1207,
                name: '1207'
            }, {
                id: 1208,
                name: '1208'
            }, {
                id: 1301,
                name: '1301'
            }, {
                id: 1302,
                name: '1302'
            }, {
                id: 1303,
                name: '1303'
            }, {
                id: 1304,
                name: '1304'
            }, {
                id: 1305,
                name: '1305'
            }, {
                id: 1306,
                name: '1306'
            }, {
                id: 1307,
                name: '1307'
            }, {
                id: 1308,
                name: '1308'
            }, {
                id: 1401,
                name: '1401'
            }, {
                id: 1402,
                name: '1402'
            }, {
                id: 1403,
                name: '1403'
            }, {
                id: 1404,
                name: '1404'
            }, {
                id: 1405,
                name: '1405'
            }, {
                id: 1406,
                name: '1406'
            }, {
                id: 1407,
                name: '1407'
            }, {
                id: 1408,
                name: '1408'
            }, {
                id: 1501,
                name: '1501'
            }, {
                id: 1502,
                name: '1502'
            }, {
                id: 1503,
                name: '1503'
            }, {
                id: 1504,
                name: '1504'
            }, {
                id: 1505,
                name: '1505'
            }, {
                id: 1506,
                name: '1506'
            }, {
                id: 1507,
                name: '1507'
            }, {
                id: 1508,
                name: '1508'
            }, {
                id: 1601,
                name: '1601'
            }, {
                id: 1602,
                name: '1602'
            }, {
                id: 1603,
                name: '1603'
            }, {
                id: 1604,
                name: '1604'
            }, {
                id: 1605,
                name: '1605'
            }, {
                id: 1606,
                name: '1606'
            }, {
                id: 1607,
                name: '1607'
            }, {
                id: 1608,
                name: '1608'
            }, {
                id: 1701,
                name: '1701'
            }, {
                id: 1702,
                name: '1702'
            }, {
                id: 1703,
                name: '1703'
            }, {
                id: 1704,
                name: '1704'
            }, {
                id: 1705,
                name: '1705'
            }, {
                id: 1706,
                name: '1706'
            }]
        }]
    }]
}, {
    id: 2,
    name: '铂爵郡',
    buildings: [{
        id: 1,
        name: '一号楼',
        units: [{
            id: 1,
            name: '一单元',
            houseNumbers: [{
                id: 101,
                name: '101'
            }, {
                id: 102,
                name: '102'
            }, {
                id: 201,
                name: '201'
            }, {
                id: 202,
                name: '202'
            }, {
                id: 203,
                name: '203'
            }, {
                id: 301,
                name: '301'
            }, {
                id: 302,
                name: '302'
            }, {
                id: 303,
                name: '303'
            }, {
                id: 401,
                name: '401'
            }, {
                id: 402,
                name: '402'
            }, {
                id: 403,
                name: '403'
            }, {
                id: 501,
                name: '501'
            }, {
                id: 502,
                name: '502'
            }, {
                id: 503,
                name: '503'
            }, {
                id: 601,
                name: '601'
            }, {
                id: 602,
                name: '602'
            }, {
                id: 603,
                name: '603'
            }]
        }, {
            id: 2,
            name: '二单元',
            houseNumbers: [{
                id: 101,
                name: '101'
            }, {
                id: 102,
                name: '102'
            }, {
                id: 201,
                name: '201'
            }, {
                id: 202,
                name: '202'
            }, {
                id: 203,
                name: '203'
            }, {
                id: 301,
                name: '301'
            }, {
                id: 302,
                name: '302'
            }, {
                id: 303,
                name: '303'
            }, {
                id: 401,
                name: '401'
            }, {
                id: 402,
                name: '402'
            }, {
                id: 403,
                name: '403'
            }, {
                id: 501,
                name: '501'
            }, {
                id: 502,
                name: '502'
            }, {
                id: 503,
                name: '503'
            }, {
                id: 601,
                name: '601'
            }, {
                id: 602,
                name: '602'
            }, {
                id: 603,
                name: '603'
            }]
        }, {
            id: 3,
            name: '三单元',
            houseNumbers: [{
                id: 101,
                name: '101'
            }, {
                id: 102,
                name: '102'
            }, {
                id: 201,
                name: '201'
            }, {
                id: 202,
                name: '202'
            }, {
                id: 203,
                name: '203'
            }, {
                id: 301,
                name: '301'
            }, {
                id: 302,
                name: '302'
            }, {
                id: 303,
                name: '303'
            }, {
                id: 401,
                name: '401'
            }, {
                id: 402,
                name: '402'
            }, {
                id: 403,
                name: '403'
            }, {
                id: 501,
                name: '501'
            }, {
                id: 502,
                name: '502'
            }, {
                id: 503,
                name: '503'
            }, {
                id: 601,
                name: '601'
            }, {
                id: 602,
                name: '602'
            }, {
                id: 603,
                name: '603'
            }]
        }, {
            id: 4,
            name: '四单元',
            houseNumbers: [{
                id: 101,
                name: '101'
            }, {
                id: 102,
                name: '102'
            }, {
                id: 201,
                name: '201'
            }, {
                id: 202,
                name: '202'
            }, {
                id: 203,
                name: '203'
            }, {
                id: 301,
                name: '301'
            }, {
                id: 302,
                name: '302'
            }, {
                id: 303,
                name: '303'
            }, {
                id: 401,
                name: '401'
            }, {
                id: 402,
                name: '402'
            }, {
                id: 403,
                name: '403'
            }, {
                id: 501,
                name: '501'
            }, {
                id: 502,
                name: '502'
            }, {
                id: 503,
                name: '503'
            }, {
                id: 601,
                name: '601'
            }, {
                id: 602,
                name: '602'
            }, {
                id: 603,
                name: '603'
            }]
        }]
    }, {
        id: 2,
        name: '二号楼',
        units: [{
            id: 1,
            name: '一单元',
            houseNumbers: [{
                id: 101,
                name: '101'
            }, {
                id: 102,
                name: '102'
            }, {
                id: 201,
                name: '201'
            }, {
                id: 202,
                name: '202'
            }, {
                id: 301,
                name: '301'
            }, {
                id: 302,
                name: '302'
            }, {
                id: 401,
                name: '401'
            }, {
                id: 402,
                name: '402'
            }]
        }, {
            id: 2,
            name: '二单元',
            houseNumbers: [{
                id: 101,
                name: '101'
            }, {
                id: 102,
                name: '102'
            }, {
                id: 201,
                name: '201'
            }, {
                id: 202,
                name: '202'
            }, {
                id: 301,
                name: '301'
            }, {
                id: 302,
                name: '302'
            }, {
                id: 401,
                name: '401'
            }, {
                id: 402,
                name: '402'
            }, {
                id: 501,
                name: '501'
            }, {
                id: 502,
                name: '502'
            }, {
                id: 601,
                name: '601'
            }, {
                id: 602,
                name: '602'
            }]
        }, {
            id: 3,
            name: '三单元',
            houseNumbers: [{
                id: 101,
                name: '101'
            }, {
                id: 102,
                name: '102'
            }, {
                id: 201,
                name: '201'
            }, {
                id: 202,
                name: '202'
            }, {
                id: 301,
                name: '301'
            }, {
                id: 302,
                name: '302'
            }, {
                id: 401,
                name: '401'
            }, {
                id: 402,
                name: '402'
            }, {
                id: 501,
                name: '501'
            }, {
                id: 502,
                name: '502'
            }, {
                id: 601,
                name: '601'
            }, {
                id: 602,
                name: '602'
            }]
        }, {
            id: 4,
            name: '四单元',
            houseNumbers: [{
                id: 101,
                name: '101'
            }, {
                id: 102,
                name: '102'
            }, {
                id: 201,
                name: '201'
            }, {
                id: 202,
                name: '202'
            }, {
                id: 301,
                name: '301'
            }, {
                id: 302,
                name: '302'
            }, {
                id: 401,
                name: '401'
            }, {
                id: 402,
                name: '402'
            }, {
                id: 501,
                name: '501'
            }, {
                id: 502,
                name: '502'
            }]
        }]
    }, {
        id: 3,
        name: '三号楼',
        units: [{
            id: 1,
            name: '一单元',
            houseNumbers: [{
                id: 101,
                name: '101'
            }, {
                id: 102,
                name: '102'
            }, {
                id: 201,
                name: '201'
            }, {
                id: 202,
                name: '202'
            }, {
                id: 301,
                name: '301'
            }, {
                id: 302,
                name: '302'
            }, {
                id: 401,
                name: '401'
            }, {
                id: 402,
                name: '402'
            }, {
                id: 501,
                name: '501'
            }, {
                id: 502,
                name: '502'
            }]
        }, {
            id: 2,
            name: '二单元',
            houseNumbers: [{
                id: 101,
                name: '101'
            }, {
                id: 102,
                name: '102'
            }, {
                id: 201,
                name: '201'
            }, {
                id: 202,
                name: '202'
            }, {
                id: 301,
                name: '301'
            }, {
                id: 302,
                name: '302'
            }, {
                id: 401,
                name: '401'
            }, {
                id: 402,
                name: '402'
            }, {
                id: 501,
                name: '501'
            }, {
                id: 502,
                name: '502'
            }, {
                id: 601,
                name: '601'
            }, {
                id: 602,
                name: '602'
            }]
        }, {
            id: 3,
            name: '三单元',
            houseNumbers: [{
                id: 101,
                name: '101'
            }, {
                id: 102,
                name: '102'
            }, {
                id: 201,
                name: '201'
            }, {
                id: 202,
                name: '202'
            }, {
                id: 301,
                name: '301'
            }, {
                id: 302,
                name: '302'
            }, {
                id: 401,
                name: '401'
            }, {
                id: 402,
                name: '402'
            }, {
                id: 501,
                name: '501'
            }, {
                id: 502,
                name: '502'
            }, {
                id: 601,
                name: '601'
            }, {
                id: 602,
                name: '602'
            }]
        }, {
            id: 4,
            name: '四单元',
            houseNumbers: [{
                id: 101,
                name: '101'
            }, {
                id: 102,
                name: '102'
            }, {
                id: 201,
                name: '201'
            }, {
                id: 202,
                name: '202'
            }, {
                id: 301,
                name: '301'
            }, {
                id: 302,
                name: '302'
            }, {
                id: 401,
                name: '401'
            }, {
                id: 402,
                name: '402'
            }, {
                id: 501,
                name: '501'
            }, {
                id: 502,
                name: '502'
            }]
        }]
    }, {
        id: 4,
        name: '四号楼',
        units: [{
            id: 1,
            name: '一单元',
            houseNumbers: [{
                id: 101,
                name: '101'
            }, {
                id: 102,
                name: '102'
            }, {
                id: 103,
                name: '103'
            }, {
                id: 201,
                name: '201'
            }, {
                id: 202,
                name: '202'
            }, {
                id: 203,
                name: '203'
            }, {
                id: 301,
                name: '301'
            }, {
                id: 302,
                name: '302'
            }, {
                id: 303,
                name: '303'
            }, {
                id: 401,
                name: '401'
            }, {
                id: 402,
                name: '402'
            }, {
                id: 403,
                name: '403'
            }]
        }, {
            id: 2,
            name: '二单元',
            houseNumbers: [{
                id: 101,
                name: '101'
            }, {
                id: 102,
                name: '102'
            }, {
                id: 103,
                name: '103'
            }, {
                id: 201,
                name: '201'
            }, {
                id: 202,
                name: '202'
            }, {
                id: 203,
                name: '203'
            }, {
                id: 301,
                name: '301'
            }, {
                id: 302,
                name: '302'
            }, {
                id: 303,
                name: '303'
            }, {
                id: 401,
                name: '401'
            }, {
                id: 402,
                name: '402'
            }, {
                id: 403,
                name: '403'
            }, {
                id: 501,
                name: '501'
            }, {
                id: 502,
                name: '502'
            }, {
                id: 503,
                name: '503'
            }]
        }, {
            id: 3,
            name: '三单元',
            houseNumbers: [{
                id: 101,
                name: '101'
            }, {
                id: 102,
                name: '102'
            }, {
                id: 103,
                name: '103'
            }, {
                id: 201,
                name: '201'
            }, {
                id: 202,
                name: '202'
            }, {
                id: 203,
                name: '203'
            }, {
                id: 301,
                name: '301'
            }, {
                id: 302,
                name: '302'
            }, {
                id: 303,
                name: '303'
            }, {
                id: 401,
                name: '401'
            }, {
                id: 402,
                name: '402'
            }, {
                id: 403,
                name: '403'
            }, {
                id: 501,
                name: '501'
            }, {
                id: 502,
                name: '502'
            }, {
                id: 503,
                name: '503'
            }]
        }, {
            id: 4,
            name: '四单元',
            houseNumbers: [{
                id: 101,
                name: '101'
            }, {
                id: 102,
                name: '102'
            }, {
                id: 103,
                name: '103'
            }, {
                id: 201,
                name: '201'
            }, {
                id: 202,
                name: '202'
            }, {
                id: 203,
                name: '203'
            }, {
                id: 301,
                name: '301'
            }, {
                id: 302,
                name: '302'
            }, {
                id: 303,
                name: '303'
            }, {
                id: 401,
                name: '401'
            }, {
                id: 402,
                name: '402'
            }, {
                id: 403,
                name: '403'
            }]
        }]
    }, {
        id: 5,
        name: '五号楼',
        units: [{
            id: 1,
            name: '一单元',
            houseNumbers: [{
            }, {
                id: 201,
                name: '201'
            }, {
                id: 202,
                name: '202'
            }, {
                id: 301,
                name: '301'
            }, {
                id: 302,
                name: '302'
            }, {
                id: 401,
                name: '401'
            }, {
                id: 402,
                name: '402'
            }, {
                id: 501,
                name: '501'
            }, {
                id: 502,
                name: '502'
            }, {
                id: 601,
                name: '601'
            }, {
                id: 602,
                name: '602'
            }]
        }, {
            id: 2,
            name: '二单元',
            houseNumbers: [{
            }, {
                id: 201,
                name: '201'
            }, {
                id: 202,
                name: '202'
            }, {
                id: 301,
                name: '301'
            }, {
                id: 302,
                name: '302'
            }, {
                id: 401,
                name: '401'
            }, {
                id: 402,
                name: '402'
            }, {
                id: 501,
                name: '501'
            }, {
                id: 502,
                name: '502'
            }, {
                id: 601,
                name: '601'
            }, {
                id: 602,
                name: '602'
            }]
        }]
    }]
}]);
